services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend  # Set the context to the backend folder
      dockerfile: Dockerfile  # Ensure this matches the Dockerfile's location inside the backend folder
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app  # Mount only the backend directory
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DB_URL}
      BACKEND_PORT: ${BACKEND_PORT}
    env_file:
      - .env
      
  frontend:
    build:
      context: ./frontend  # Make sure this matches your frontend folder path
      dockerfile: Dockerfile  # Optional if your Dockerfile is named 'Dockerfile'
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
  node_modules:
