services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
      - backend/.env.test
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DB_URL}
      ENV: ${ENV}
      BACKEND_PORT: ${BACKEND_PORT}
      PYTHONPATH: /app

    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  music-service:
    build:
      context: ./music-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./music-service:/app
    depends_on:
      - db
      - backend
    env_file:
      - .env
      - music-service/.env.test
    environment:
      DATABASE_URL: ${DB_URL}
      ENV: ${ENV}
      MUSIC_SERVICE_PORT: ${MUSIC_SERVICE_PORT}
      PYTHONPATH: /app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://music-service:8001/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.vite
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - music-service
    environment:
      VITE_API_URL: http://localhost:8000
      REACT_APP_MUSIC_API_URL: http://localhost:8001
      NODE_ENV: development
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/health"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local