"""updated favorites to support albums and artists

Revision ID: 322f8032e892
Revises: d51b7a44f7b6
Create Date: 2025-05-31 08:12:39.034786

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "322f8032e892"
down_revision: Union[str, None] = "d51b7a44f7b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "favorites", sa.Column("spotify_id", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "favorites",
        sa.Column(
            "type",
            sa.Enum("track", "album", "artist", name="favoritetype"),
            nullable=False,
        ),
    )
    op.drop_column("favorites", "spotify_track_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "favorites",
        sa.Column(
            "spotify_track_id",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("favorites", "type")
    op.drop_column("favorites", "spotify_id")
    # ### end Alembic commands ###
