"""final_schema

Revision ID: e9db39654fa9
Revises: 
Create Date: 2025-06-18 19:22:12.098779
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# Alembic revision identifiers
revision: str = 'e9db39654fa9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
